apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    environment: dev-01
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      environment: dev-01
  template:
    metadata:
      labels:
        app: nginx
        environment: dev-01
    spec:
      containers:
      - image: nginx:1.15
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    environment: dev-01
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
    environment: dev-01
  type: ClusterIP
