apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    environment: dev-01
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
    environment: dev-01
  type: ClusterIP
